package driver;

import dao.RepayRequestDao;
import dao.UserDao;
import dao.UserTypeDao;
import model.RepayRequest;
import model.User;
import model.UserType;

public class Driver {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		
	//to create user already exist in table	with exisitng id; can be use to create the repay request in repay request table
		
	
//	User user = new User( 1 ,"hien", "tran", "ht12345", "8976", "employee");
	//----------------------------------------------------------------------------------	
	//create new user to insert into table withput id ; id will be generated by database
	
		UserDao userdao = new UserDao();
	//must create a type object first to link to user type table; so later we can get the type of user either employyee or manager; 
		//create usertype object first ; one for employee; one for manger then add to db; user type table should only have two rows ;
		//one for manger and one for employee
		//;then create usertype object with matching id and put in the user object and put in user table;
		//it should link the new created user to the one in user role table;
		//this is for test purpose
		
		//create employe typr object
//		UserType usertype = new UserType("manager");
		//use usertype dao to add to usertype table
		UserTypeDao usertypeDao = new UserTypeDao();
		
//		usertypeDao.insert(usertype);
	
		
		
		//create user type with id from usertype table; this usertype row already in user type table
		UserType usertype = new UserType(1, "employee");
		User user = new User("daragon", "black", "dbt12345", "4567",  usertype);
		
		
		
	userdao.insert(user);
		
		//--------------------------------------------------------------------------------------
		//to create a new request using the user already exist
//		RepayRequest repayRequest = new RepayRequest(4568745, 100, "pending","food", user);

		
//		RepayRequestDao repayRequestDao = new RepayRequestDao();
//		repayRequestDao.insert(repayRequest);
				
//			userdao.insert(user);
		
//		userdao.update(user);
//System.out.println(userdao.selectUser(1));	
		
		
		
	}

}
